# Site settings
title: Airi/Phuong Pham
email: pride.blue239@eagereverest.com
description: > # keep this and put description below
  Tech Artist & Graphics Programmer
url: "https://phuongpham7112.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/phuong-pham-airi/"
github_username: PhuongPham7112
artstation_url: "https://airi_chan.artstation.com/"
footer_text: "Made with ðŸ©µ by Airi"
paginate: 9
paginate_path: "/page:num/"
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
